# Generated by Django 6.0.2 on 2026-02-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_add_session_key_to_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(unique=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('generated', 'Generated'),
                            ('publish_pending', 'Publish pending'),
                            ('published', 'Published'),
                            ('failed', 'Failed'),
                        ],
                        default='generated',
                        max_length=20,
                    ),
                ),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('public_image_url', models.URLField(blank=True, max_length=500)),
                ('result_label', models.CharField(blank=True, max_length=120)),
                ('good_count', models.PositiveIntegerField(default=0)),
                ('bad_count', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('good_pct_display', models.PositiveSmallIntegerField(default=0)),
                ('bad_pct_display', models.PositiveSmallIntegerField(default=0)),
                ('creation_id', models.CharField(blank=True, max_length=100)),
                ('instagram_media_id', models.CharField(blank=True, max_length=100)),
                ('last_error', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'publicacion diaria',
                'verbose_name_plural': 'Publicaciones diarias',
                'ordering': ['-publication_date'],
            },
        ),
    ]
