# Generated by Django 6.0.2 on 2026-02-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_dailypublication'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramTokenState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'provider',
                    models.CharField(
                        choices=[('facebook_graph', 'Facebook Graph'), ('instagram_graph', 'Instagram Graph')],
                        default='facebook_graph',
                        max_length=20,
                    ),
                ),
                ('access_token', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('data_access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('token_type', models.CharField(blank=True, max_length=40)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'estado token instagram',
                'verbose_name_plural': 'Estados token instagram',
            },
        ),
    ]
