# Generated by Django 6.0.2 on 2026-02-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_instagramtokenstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at'], 'verbose_name': 'voto (encuesta)', 'verbose_name_plural': 'Votos (encuesta)'},
        ),
    ]
